### ISSUE TITLE
api search only 20 scenes 

### ISSUE THREAD

**Issue by yueyin1992** [yannforget/landsatxplore#12]
Hi, 

I am trying api search and the scenes only return 20 scenes. It seems like the first 20 images. 
Here are my codes:
scenes = api.search(
    ...:     dataset='SP_TILE_DSWE',
    ...:     latitude=41.33,
    ...:     longitude=-72.80,
    ...:     start_date='2004-01-01',
    ...:     end_date='2018-12-31',
    ...:     max_cloud_cover=10)
Yue

**Comment by yannforget** [comment]
Hi,

Yes, it's the default limit. You can use the `max_results` parameter to increase it:

``` python
scenes = api.search(
    dataset='SP_TILE_DSWE',
    latitude=41.33,
    longitude=-72.80,
    start_date='2004-01-01',
    end_date='2018-12-31',
    max_cloud_cover=10,
    max_results=50
```

**Comment by yueyin1992** [comment]
Thanks a lot. It is well solved. Can I know if I can use the codes to download landsat products like dynamic water surface extent? I can find the dataset name, which is " SP_TILE_DSWE ". But it gives errors when I am trying to download. I don't know how to revise the codes. Thanks!

**Comment by yannforget** [comment]
Yes, we would have to change  the `EE_DOWNLOAD_URL` or the `EE_FOLDER` constants depending on the download URL  for the DWSE products:

``` python
EE_DOWNLOAD_URL = 'https://earthexplorer.usgs.gov/download/{folder}/{sid}/STANDARD/EE'
EE_FOLDER = {
    'LANDSAT_TM_C1': '12266',
    'LANDSAT_ETM_C1': '12267',
    'LANDSAT_8_C1': '12864'
}
```
For now it only works for three datasets.

**Comment by griembauer** [comment]
Hello,
Thanks for the great tool! A follow-up question for this issue: 
Where exactly do these hashes (?) for building the download URL come from?
```
DATASETS = {
    "LANDSAT_TM_C1": "5e83d08fd9932768",
    "LANDSAT_ETM_C1": "5e83a507d6aaa3db",
    "LANDSAT_8_C1": "5e83d0b84df8d8c2"
```
I am currently trying to also download Sentinel-2 data using landsatxplore, because downloading it from ESA's scihub (and sentinelsat etc.) is now harder as old data moved into a longterm archive. Searching for S2-Data already works by using the "Sentinel_2A" dataset name. However, I cannot figure out the constant for S2-Data.
Thanks,
Guido
