### ISSUE TITLE
question about EE_folder

### ISSUE THREAD

**Issue by tongqiugeog** [yannforget/landsatxplore#3]
Hi Yann,

Just have a quick question about the "EE_folder" and "EE_size" in your code.

EE_FOLDER = {
    'LANDSAT_TM_C1': '12266',
    'LANDSAT_ETM_C1': '12267',
    'LANDSAT_8_C1': '12864'
}
SIZES = {
    'LANDSAT_TM_C1': 150 * 1024**2,
    'LANDSAT_ETM_C1': 235 * 1024**2,
    'LANDSAT_8_C1': 919 * 1024**2
}
I wonder where did you find such information? 

Thank you very much for your help.

Best,
Tong

**Comment by yannforget** [comment]
Hi,

Yes, it's quite hacky. 

For the `folder` variable, I just compared the URLs depending on the satellite platform in the EarthExplorer's interface. I still don't know the meaning of this numbers.

For the `size` variable, it is an estimation of the size of a dataset depending on the mission. This is because the information is not available in the HTTP headers (same thing when you download a scene with your browser -- there isn't any progress bar).

To be honest, I am rewriting everything based on the Public Cloud Dataset from Google. Download speeds are a lot better and credentials aren't needed. It's already working so don't hesitate to tell me if you are interested.

**Comment by tongqiugeog** [comment]
Hi,

I am very interested in the Public Cloud Dataset downloading. I wonder is the Landsat analysis ready dataset (ARD) also on that platform?

Best,
Tong

**Comment by yannforget** [comment]
Hi,
Here is a first version: https://github.com/yannforget/pylandsat
ARD is not available in the public google cloud dataset.
Yann

**Comment by tongqiugeog** [comment]
Hi,

Thank you very much for sharing the code. I will close this issue.

Best,
Tong
